version: '3.4'

services:
  postgres:
    image: postgres:15.4-alpine
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assets
      - DATABASE_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - $PWD/volumes/postgres:/var/lib/postgresql/data
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/database.sql
volumes:
  postgres:
    driver: local
